config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "homes#top"
  get "/home/about" => "homes#about"
  get "/search" => "searches#searches", as: "search"
  resources :users, only: [:show, :index, :edit, :update,] do
    resource :relationships, only: [:create, :destroy]
    #memberは個別idがあり
    get :followings, on: :member
    get :followers, on: :member
  end
    
  resources :books, only: [:create, :index, :edit, :show, :destroy, :update] do
    resources :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
  
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  
  def create
    @book = Book.find(params[:book_id])
    #favorite = current_user.favorites.new(book_id: book.id)
    favorite = Favorite.new
    favorite.user_id = current_user.id
    favorite.book_id = @book.id
    favorite.save
  end
  
  def destroy
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: @book.id)
    favorite.destroy
  end
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/views/favorites/_favorites.html.erb
<% if book.favorited_by?(current_user) %>
  <%= link_to book_favorites_path(book.id), method: :delete, remote: true do %>
    ❤<%= book.favorites.count %>
  <% end %>
<% else %>
 <%= link_to book_favorites_path(book.id), method: :post, remote: true do %>
    ♡<%= book.favorites.count %>
 <% end %>
<% end %>

app/views/favorites/create.js.erb
$('#favorite_buttons_<%= @book.id %>').html('<%= j (render partial: 'favorites/favorites', locals: { book: @book}) %>');

alert("いいねを解除しました")

app/views/favorites/destroy.js.erb
$('#favorite_buttons_<%= @book.id %>').html('<%= j (render partial: 'favorites/favorites', locals: { book: @book}) %>');

alert("いいねを解除しました")