config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "homes#top"
  get "/home/about" => "homes#about"
  get "/search" => "searches#searches", as: "search"
  resources :users, only: [:show, :index, :edit, :update,] do
    resource :relationships, only: [:create, :destroy]
    #memberは個別idがあり
    get :followings, on: :member
    get :followers, on: :member
  end
    
  resources :books, only: [:create, :index, :edit, :show, :destroy, :update] do
    resources :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates :comment, presence: true
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  def create
    @book = Book.find(params[:book_id])
    @book_comment = BookComment.new(comment_params)
    @book_comment.user_id = current_user.id
    @book_comment.book_id = @book.id
    @book_comment.save
    @user = current_user
  end

  def destroy
    BookComment.find_by(id: params[:id], book_id: params[:book_id]).destroy
    @book = Book.find(params[:book_id])
    @user = current_user
  end

  private
  def comment_params
    params.require(:book_comment).permit(:comment)
  end

end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/views/book_comments/_comment_table.html.erb
<% book.book_comments.each do |comment| %>
 <%= link_to user_path(@user.id) do %>
  <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, format: "jpg", fallback: "no_image.jpg" %>
  <p><%= @user.name %></p>
 <% end %>
 <p><%= comment.comment %></p>
 <%= link_to "Destroy", book_book_comment_path(book.id, comment.id), method: :delete, remote: true %>
<% end %>

app/views/book_comments/create.js.erb
$("#comment_table").html("<%= j (render partial: "book_comments/comment_table", locals: { book: @book, user: @user }) %>");
$(".input_comment").val("")
alert("コメントをしました")

app/views/book_comments/destroy.js.erb
$("#comment_table").html("<%= j (render partial: "book_comments/comment_table", locals: { book: @book, user: @user }) %>");

alert("コメントを削除しました")