config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "homes#top"
  get "/home/about" => "homes#about"
  get "/search" => "searches#searches", as: "search"
  resources :users, only: [:show, :index, :edit, :update,] do
    resource :relationships, only: [:create, :destroy]
    #memberは個別idがあり
    get :followings, on: :member
    get :followers, on: :member
  end
    
  resources :books, only: [:create, :index, :edit, :show, :destroy, :update] do
    resources :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  #自分がフォローする側の関係性
  has_many :active_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  #自分がフォローしている人を見たい（active_relationshipsを通じてRelationshipテーブルを参照）
  has_many :following, through: :active_relationships, source: :followed
  #自分がフォローされる側の関係性
  has_many :passive_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :follower, through: :passive_relationships, source: :follower


  # createメソッド（モデルのインスタンス生成と保存を同時に行う）
  def follow(another_user)
    unless self == another_user
      self.active_relationships.find_or_create_by(followed_id: another_user.id)
      #active_relationships.find_or_create_by(followed_id: user_id) user_idだと同じ人をフォローしてしまう
    end
  end

  def unfollow(user_id)
    active_relationships.find_by(followed_id: user_id).destroy
  end

  def following?(another_user)
    self.following.include?(another_user)
  end

  attachment :profile_image

  validates :name, presence: true, uniqueness: true, length: { in: 2..20 }
  validates :introduction, length: { maximum: 50 }
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @book = Book.new
    @books = @user.books
  end

  def index
    @users = User.all
    @user = current_user
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
    if current_user.id != @user.id
      redirect_to user_path(current_user)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user.id)
      flash[:notice] = "You have update user successfully."
    else
      render "edit"
    end
  end

  def destroy
    user = User.find(params.id)
    user.destroy
    redirect_to users_path
  end

  def followings
    @users = User.find(params[:id]).following.where.not(id: current_user.id)
  end

  def followers
    @users = User.find(params[:id]).follower.where(id: current_user.id)
  end

  private
  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_index.html.erb
<table class='table'>
  <thead>
   <tr>
    <th>image</th>
    <th>name</th>
    <th colspan="3"></th>
   </tr>
  </thead>
  <tbody>
   <% users.each do |user| %>
    <tr>
      <%# User.find(book.id)でもいい %>
      <td><%= attachment_image_tag user, :profile_image, :fill, 100, 100, format: "jpg", fallback: "no_image.jpg" %></td>
      <td><%= user.name %></td>
      <td>フォロー数：<%= user.following.count %></td>
      <td>フォロワー数：<%= user.follower.count%></td>
      <% unless user == current_user %>
       <% if current_user.following?(user) %>
        <td>
         <%= link_to "フォローを外す", user_relationships_path(user), method: :delete %>
        </td>
       <% else %>
        <td>
         <%= link_to "フォローをする", user_relationships_path(user), method: :post %>
        </td>
       <% end %>
      <% end %>
      <td><%= link_to "Show", user_path(user.id) %></td>
   <% end %>
  </tbody>
</table>

app/views/users/_info.html.erb
<table class='table'>
 <tr><%= attachment_image_tag user,:profile_image, :fill, 40, 40, format: "jpg", fallback: "no_image.jpg" %></tr>
 <tr>
  <th><h4>name</h4></th>
  <%#ログインしているユーザーを表示%>
  <th><%= user.name %></th>
 </tr>
 <tr>
  <th><h4>introduction</h4></th>
  <%#ログインしているユーザーを表示%>
  <th><%= user.introduction %></th>
 </tr>
 <tr>
  <th><h4>follows</h4></th>
  <th><%= link_to user.following.count, followings_user_path(user.id) %></th>
 </tr>
 <tr>
  <th><h4>foolwers</h4></th>
  <th><%= link_to user.follower.count, followers_user_path(user.id) %></th>
 </tr>
</table>

 <div class='row'>
  <% unless user == current_user %>
   <% if current_user.following?(user) %>
    <%= link_to "フォローを外す", user_relationships_path(user), method: :delete, class: "btn btn-primary" %>
   <% else %>
    <%= link_to "フォロー", user_relationships_path(user), method: :post, class: "btn btn-success" %>
   <% end %>
  <% end %>
  <%= link_to edit_user_path(user), class:"btn btn-outline-secondary btn-block fas fa-user-cog" do %>
   <i class="fas fa-user-cog"></i>
  <% end %>
 </div>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>User info</h2>
    <% if @user.errors.any? %>
     <%= @user.errors.count %>
     <% @user.errors.full_messages.each do |message| %>
      <%= message %>
     <% end %>
    <% end %>
     <%= form_with model: @user, local:true do |f| %>
      <div class="form-group">
        <label for="user_name">Name</label>
        <p><%= f.text_field :name %></p>
      </div>
      <div class="form-group">
        <label for="user_image">Image</label>
        <p><%= f.attachment_field :profile_image, fallback: "no-image.png" %></p>
      </div>
      <div class="form-group">
        <label for="user_introduction">Introduction</label>
        <p><%= f.text_area :introduction %></p>
      </div>
      <div class="form-group">
        <p><%= f.submit "Update User" %></p>
      </div>
     <% end %>
     </div>
  </div>
</div>

app/views/users/followers.html.erb
<h1>followed</h1>

<table class="table">
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= attachment_image_tag user,:profile_image, :fill, 40, 40, format: "jpg", fallback: "no_image.jpg" %></td>
        <td><%= user.name %></td>
        <td>フォロー数：<%= user.following.count %></td>
        <td>フォロワー数：<%= user.follower.count %></td>
        <td><%= link_to "Show", user_path(user.id) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/followings.html.erb
<h1>Following Now</h1>

<table class="table">
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= attachment_image_tag user,:profile_image, :fill, 40, 40, format: "jpg", fallback: "no_image.jpg" %></td>
        <td><%= user.name %></td>
        <td>フォロー数：<%= user.following.count %></td>
        <td>フォロワー数：<%= user.follower.count %></td>
        <td><%= link_to "Show", user_path(user.id) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
     <h1>User info</h1>
     <%= render "info", user: current_user %>
     <h2 class="mt-3">New book</h2>
     <%= render "books/form", book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
     <h2>Users</h2>
     <%= render "index", users: @users %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
     <h1>User info</h1>
     <%= render "info", user: @user%>
     <h2 class="mt-3">New book</h2>
     <%= render "books/form", book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
     <h2>Books</h2>
     <%= render "books/index", books: @books %>
    </div>
  </div>
</div>