config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "homes#top"
  get "/home/about" => "homes#about"
  get "/search" => "searches#searches", as: "search"
  resources :users, only: [:show, :index, :edit, :update,] do
    resource :relationships, only: [:create, :destroy]
    #memberは個別idがあり
    get :followings, on: :member
    get :followers, on: :member
  end
    
  resources :books, only: [:create, :index, :edit, :show, :destroy, :update] do
    resources :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  def favorited_by?(user)
    #user_id: user.idはuser_id = user.idのような関係
    favorites.where(user_id: user.id).exists?
  end

  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book.id)
      flash[:notice] = "You have created book successfully."
    else
      @books = Book.all
      render "index"
    end
  end

  def show
    @book = Book.find(params[:id])
    @user = @book.user
    @books = Book.all
    @book_new = Book.new
    @book_comment = BookComment.new
  end

  def index
    @books = Book.all
    @book = Book.new
    @user = current_user
  end

  def edit
    @book = Book.find(params[:id])
    # ==を使用する時は同じ単位で記述する
    if @book.user == current_user
      #renderがなくても同じ動作をする
      render "edit"
    else
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book.id)
      flash[:notice] = "You have updated book successfully."
    else
      render "edit"
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end

  private
  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<%= form_with model: book, local:true do |f| %>
  <div class="form-group">
    <label for="book_title">Title</label>
    <p><%= f.text_field :title %></p>
  </div>
  <div class="form-group">
    <label for="book_title">Opinion</label>
    <p><%= f.text_area :body %></p>
  </div>
  <div class="form-group">
    <p><%= f.submit "Create Book" %></p>
  </div>
<% end %>

app/views/books/_index.html.erb
<table class='table table-hover table-inverse'>
  <thead>
   <tr>
    <th></th>
    <th>Title</th>
    <th>Opinion</th>
    <th colspan="3"></th>
   </tr>
  </thead>
  <tbody>
   <% books.each do |book| %>
    <tr>
      <td><%= link_to user_path(book.user_id) do %>
      <%= attachment_image_tag User.find(book.user_id), :profile_image, :fill, 40, 40, format: "jpg", fallback: "no_image.jpg" %></td>
      <% end %>
      <td><%= link_to book.title, book_path(book.id) %></td>
      <td><%= book.body %></td>
      <td id="favorite_buttons_<%= book.id %>">
       <%= render partial: "favorites/favorites", locals: { book: book} %>
      </td>
      <td>コメント数<%= book.book_comments.count %></td>
    </tr>
   <% end %>
  </tbody>
</table>

app/views/books/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  		<h1>Editing Book</h1>
    	<% if @book.errors.any? %>
       <%= @book.errors.count %>errors prohibited this obj from being saved: %>
       <% @book.errors.full_messages.each do |message| %>
        <ul>
          <li>
            <%= message %>
          </li>
        </ul>
       <% end %>
      <% end %>
        <%= form_with model: @book, local:true do |f| %>
      	  <div class="form-group">
            <label for="book_title">Title</label>
            <br><%= f.text_field :title %>
          </div>
          <div class="form-group">
            <label for="book_opinion">Opinion</label>
            <p><%= f.text_area :body %>
          </div>
          <div class="form-group">
            <p><%= f.submit "Update Book" %></p>
          </div>
          <%= link_to "Show", book_path(@book) %>
          |
          <%= link_to "Back", books_path %>
        <% end %>
      </div>
    </div>
</div>

app/views/books/index.html.erb
<div class="errors">
  <% if @book.errors.any? %>
   <%= @book.errors.count %>
   <% @book.errors.full_messages.each do |message| %>
    <%= message %>
   <% end %>
  <% end %>
</div>
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h1>User info</h1>
      <%= render "users/info", user: current_user  %>
      <h2 class="mt-3">New book</h2>
      <%= render "form", book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
     <h1>Books</h1>
     <%= render "index", books: @books %>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
     <h1>User info</h1>
     <%= render "users/info", user: @user %>
     <h2 class="mt-3">New book</h2>
     <%= render "form", book: @book_new %>
    </div>
    <div class='col-md-8 offset-md-1'>
     <h2>Book detail</h2>
     <table class='table'>
      <tbody>
        <tr>
          <td><%= link_to user_path(@user.id) do %>
             <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, format: "jpg", fallback: "no_image.jpg" %>
             <%= @user.name %>
             <% end %>
          </td>
          <td><%= link_to @book.title, book_path(@book.id) %></td>
          <td><%= @book.body %></td>
          <%# 変数が左辺、データなどの値が右辺　%>
          <% if @user == current_user %>
           <td><%= link_to "Edit", edit_book_path %></td>
           <td><%= link_to "Destroy", book_path, method: :delete, data: {confirm: "本当に消しますか？"} %></td>
          <% end %>
          <td>コメント数：<%= @book.book_comments.count %> </td>
        </tr>
      </tbody>
     </table>
     <div id="comment_table">
      <%= render partial: "book_comments/comment_table", locals: {book: @book, user: @user} %>
     </div>
       <%= form_with(model:[@book, @book_comment]) do |f| %>
         <%= f.text_area :comment, class: "input_comment", rows:"5" %>
         <%= f.submit "送信" %>
       <% end %>
    </div>
 </div>
</div>